"""Validation utilities for physics solver and surrogate models."""

from __future__ import annotations

import logging
from typing import Dict, Optional, Tuple

import numpy as np

logger = logging.getLogger(__name__)


def compute_error_metrics(
    pred: np.ndarray,
    target: np.ndarray,
    mask: Optional[np.ndarray] = None,
) -> Dict[str, float]:
    """Compute error metrics between predicted and target fields.

    Args:
        pred: Predicted field of shape ``(..., H, W)``.
        target: Ground truth field of shape ``(..., H, W)``.
        mask: Optional binary mask ``(H, W)`` to restrict error computation
            to specific regions (e.g., only battery cells).

    Returns:
        Dictionary of error metrics:
          - "l2_rel": Relative L2 error (normalized by target norm)
          - "l2_abs": Absolute L2 error
          - "max_abs": Maximum absolute error
          - "rmse": Root mean squared error
          - "mae": Mean absolute error
    """
    if mask is not None:
        pred_masked = pred[..., mask > 0]
        target_masked = target[..., mask > 0]
    else:
        pred_masked = pred.flatten()
        target_masked = target.flatten()

    error = pred_masked - target_masked

    l2_abs = np.linalg.norm(error)
    l2_target = np.linalg.norm(target_masked)
    l2_rel = l2_abs / (l2_target + 1e-10)

    max_abs = np.abs(error).max()
    rmse = np.sqrt(np.mean(error**2))
    mae = np.mean(np.abs(error))

    return {
        "l2_rel": float(l2_rel),
        "l2_abs": float(l2_abs),
        "max_abs": float(max_abs),
        "rmse": float(rmse),
        "mae": float(mae),
    }


def check_energy_conservation(
    T0: np.ndarray,
    T1: np.ndarray,
    rho: np.ndarray,
    cp: np.ndarray,
    dx: float,
    dy: float,
    q: float,
    dt: float,
    h_conv: float,
    T_amb: float,
) -> Tuple[float, float]:
    """Check energy conservation for a single time step.

    Args:
        T0: Initial temperature field ``(H, W)`` [K].
        T1: Final temperature field ``(H, W)`` [K].
        rho: Density field ``(H, W)`` [kg/m^3].
        cp: Specific heat field ``(H, W)`` [J/(kg*K)].
        dx: Grid spacing in x [m].
        dy: Grid spacing in y [m].
        q: Heat generation rate [W/m^3].
        dt: Time step [s].
        h_conv: Convective heat transfer coefficient [W/(m^2*K)].
        T_amb: Ambient temperature [K].

    Returns:
        Tuple of (energy_generated, energy_change) in Joules.
    """
    # Cell volume (assuming unit depth in z-direction)
    dV = dx * dy

    # Total energy change in the domain
    energy_change = np.sum(rho * cp * (T1 - T0) * dV)

    # Energy generated by heat source
    energy_generated = q * dt * dV * T0.size

    # Energy lost through boundaries (simplified)
    perimeter_length = 2 * (T0.shape[0] * dy + T0.shape[1] * dx)
    T_boundary_avg = (
        T1[0, :].mean() + T1[-1, :].mean() + T1[:, 0].mean() + T1[:, -1].mean()
    ) / 4
    energy_lost = h_conv * perimeter_length * (T_boundary_avg - T_amb) * dt

    logger.debug(
        f"Energy: generated={energy_generated:.2e} J, "
        f"lost={energy_lost:.2e} J, change={energy_change:.2e} J"
    )

    return energy_generated - energy_lost, energy_change


def validate_temperature_bounds(
    T: np.ndarray,
    T_min: float = 200.0,
    T_max: float = 500.0,
) -> bool:
    """Check if temperature field is within physical bounds.

    Args:
        T: Temperature field of any shape [K].
        T_min: Minimum allowable temperature [K].
        T_max: Maximum allowable temperature [K].

    Returns:
        True if all temperatures are within bounds, False otherwise.
    """
    is_valid = (T >= T_min).all() and (T <= T_max).all()

    if not is_valid:
        logger.warning(
            f"Temperature out of bounds: min={T.min():.2f} K, max={T.max():.2f} K "
            f"(expected range [{T_min}, {T_max}] K)"
        )

    return is_valid
